# Generated by Django 6.0.4 on 2026-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationsession',
            name='problem_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
